"""
Backtest Framework for Biotech Screener

Provides metrics calculation, IC measurement, returns providers,
and validation utilities for evaluating screener performance.
"""

from backtest.ic_measurement import (  # Main system; Engines; Core functions; Enums; Data classes; Constants
    HORIZON_TRADING_DAYS,
    IC_EXCELLENT,
    IC_GOOD,
    IC_WEAK,
    BootstrapCI,
    BootstrapEngine,
    ForwardReturn,
    ForwardReturnEngine,
    ICCalculationEngine,
    ICMeasurementSystem,
    ICQuality,
    ICResult,
    ICStabilityAnalyzer,
    ICTimeSeriesDatabase,
    MarketCapBucket,
    OutOfSampleValidator,
    RegimeType,
    RollingICResult,
    SectorCategory,
    WeeklyICReportGenerator,
    analyze_ic_trend,
    calculate_ic,
)
from backtest.metrics import (
    METRICS_VERSION,
    aggregate_metrics,
    compute_bucket_returns,
    compute_hit_rate,
    compute_period_metrics,
    compute_quintile_returns,
    compute_spearman_ic,
    run_metrics_suite,
)
from backtest.returns_provider import (
    BaseReturnsProvider,
    CSVReturnsProvider,
    FixedReturnsProvider,
    LaggedReturnsProvider,
    NullReturnsProvider,
    ShuffledReturnsProvider,
    create_csv_provider,
    create_lagged_provider,
    create_shuffled_provider,
)

__all__ = [
    # Metrics
    "compute_spearman_ic",
    "compute_bucket_returns",
    "compute_quintile_returns",
    "compute_hit_rate",
    "compute_period_metrics",
    "aggregate_metrics",
    "run_metrics_suite",
    "METRICS_VERSION",
    # IC Measurement System
    "ICMeasurementSystem",
    "WeeklyICReportGenerator",
    "ICTimeSeriesDatabase",
    "ForwardReturnEngine",
    "ICCalculationEngine",
    "BootstrapEngine",
    "ICStabilityAnalyzer",
    "OutOfSampleValidator",
    "calculate_ic",
    "analyze_ic_trend",
    "ICQuality",
    "MarketCapBucket",
    "SectorCategory",
    "RegimeType",
    "ForwardReturn",
    "ICResult",
    "BootstrapCI",
    "RollingICResult",
    "IC_EXCELLENT",
    "IC_GOOD",
    "IC_WEAK",
    "HORIZON_TRADING_DAYS",
    # Returns providers
    "BaseReturnsProvider",
    "CSVReturnsProvider",
    "NullReturnsProvider",
    "FixedReturnsProvider",
    "ShuffledReturnsProvider",
    "LaggedReturnsProvider",
    "create_csv_provider",
    "create_shuffled_provider",
    "create_lagged_provider",
]
